server:
    contextPath: /services/rest

spring:
  jpa:
    database: hsql  
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password: 

flyway:
  locations: classpath:db/migration/${spring.jpa.database}