server:
    contextPath: /services/rest

spring:
  jpa:
    database: hsql
      
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password: 

flyway:
  locations: classpath:db/migration/${spring.jpa.database}
  
  
---

spring:
  profiles: sql-server
  
  # JPA Properties
  jpa:
    database: sql-server
    
  # DataSource Properties
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BirthdayPlanner
    username: birthday_planner_user
    password: Password100